#!/usr/bin/env ruby

require "fileutils"
require "json"
require "time"
require "yaml"

ROOT = File.expand_path("..", __dir__)
SRC = File.join(ROOT, "src")
DIST = File.join(ROOT, "dist")

SOURCE_FILES = [
  { "label" => "projects", "path" => "src/data/projects.yml" },
  { "label" => "inventory", "path" => "src/data/inventory.yml" },
  { "label" => "fieldLogs", "path" => "src/data/field-logs.yml" },
  { "label" => "socialPosts", "path" => "src/data/social-posts.yml" }
].freeze

def load_yaml(path)
  YAML.safe_load(
    File.read(path),
    permitted_classes: [Date, Time],
    aliases: false
  )
end

def assert_array!(data, key, path)
  value = data.fetch(key)
  return value if value.is_a?(Array)

  abort("#{path}: expected #{key} to be an array")
end

def assert_unique!(records, key, label)
  values = records.map { |record| record.fetch(key) }
  duplicates = values.group_by(&:itself).select { |_value, group| group.length > 1 }.keys
  return if duplicates.empty?

  abort("#{label}: duplicate #{key} values: #{duplicates.join(", ")}")
end

projects_path = File.join(ROOT, "src/data/projects.yml")
inventory_path = File.join(ROOT, "src/data/inventory.yml")
field_logs_path = File.join(ROOT, "src/data/field-logs.yml")
social_posts_path = File.join(ROOT, "src/data/social-posts.yml")

projects = assert_array!(load_yaml(projects_path), "projects", projects_path)
inventory = assert_array!(load_yaml(inventory_path), "items", inventory_path)
field_logs = assert_array!(load_yaml(field_logs_path), "field_logs", field_logs_path)
social_posts =
  if File.exist?(social_posts_path)
    assert_array!(load_yaml(social_posts_path), "social_posts", social_posts_path)
  else
    []
  end

assert_unique!(projects, "id", "projects")
assert_unique!(projects, "slug", "projects")
assert_unique!(inventory, "id", "inventory")
assert_unique!(field_logs, "id", "field_logs")
assert_unique!(field_logs, "slug", "field_logs")
assert_unique!(social_posts, "id", "social_posts")
assert_unique!(social_posts, "slug", "social_posts")

project_ids = projects.map { |project| project.fetch("id") }
(inventory + field_logs).each do |record|
  next if project_ids.include?(record.fetch("associated_project"))

  abort("#{record.fetch("id")}: unknown associated_project #{record.fetch("associated_project")}")
end

archive = {
  "schemaVersion" => "0.1.0",
  "generatedAt" => Time.now.utc.iso8601,
  "meta" => {
    "name" => "Forgotten Industries",
    "type" => "archive / evidence-based memoir / technical blog",
    "tagline" => "An archive and evidence-based memoir that explores what happens to the things we leave behind: old machines, abandoned projects, and the parts of ourselves we once thought lost.",
    "voice" => "intimate, precise, archival, technical, emotionally honest",
    "sourceFiles" => SOURCE_FILES
  },
  "projects" => projects,
  "inventory" => inventory,
  "fieldLogs" => field_logs,
  "socialPosts" => social_posts
}

FileUtils.mkdir_p(DIST)

json = JSON.pretty_generate(archive)
File.write(File.join(DIST, "forgotten-industries.json"), "#{json}\n")

types = File.read(File.join(SRC, "types.ts")).strip
typescript = <<~TS
  // Generated by scripts/build.rb. Edit src/data/*.yml and src/types.ts, then run npm run build.

  #{types}

  export const archive = #{json} satisfies ForgottenIndustriesArchive;

  export const projects = archive.projects;
  export const inventory = archive.inventory;
  export const fieldLogs = archive.fieldLogs;
  export const socialPosts = archive.socialPosts;

  export default archive;
TS

File.write(File.join(DIST, "index.ts"), typescript)

puts "Wrote dist/forgotten-industries.json"
puts "Wrote dist/index.ts"
